---
# tasks file for roles/Odoo

  - name: Roda o container Odoo     
    docker_container:
      name: odoo10
      image: "odoo:10.0" 
      state: started
      restart: yes         
      links: postgres-db:db
      volumes: /var/lib/odoo/10.0
      ports: "8069:8069"
      env:
        db_password: odoo
