---
# tasks file for postgresql

  - name: Roda o container PostgreSQL
    docker_container:
      name: postgres-db
      image: "postgres:9.4"
      state: started
      restart: yes
      volumes: library/postgres/9.4
      env:
        POSTGRES_USER: odoo
        POSTGRES_PASSWORD: odoo