---
# tasks file for roles/Docker
  
  - name: Pacotes de pré instalação
    apt:
      name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip
      - python-docker
      state: latest

  - name: Adicionando a chave GPG oficial do repositório do Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Adicionando o repositorio docker
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu xenial stable"
      state: present     

  - name: Instalando o Docker
    apt:
      name: 
      - docker-ce
      state: latest 
      